apiVersion: apps/v1 
kind: Deployment
metadata:
  name: counter-app
  labels:
    app: counter-app
spec:
  selector:
    matchLabels:
      app: counter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: tarunbhardwaj/flask-counter-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        env:
        - name: REDIS_URL
          value: "redis://redis-ha-master-svc:6379/0"
        ports:
        - containerPort: 5000
          protocol: TCP
      nodeSelector:
        stack: saarah
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30 