apiVersion: apps/v1 
kind: Deployment
metadata:
  name: counter-app
  labels:
    app: counter-app
spec:
  selector:
    matchLabels:
      app: counter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: tarunbhardwaj/flask-counter-app:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_URL
          value: "redis://saarah-redis-ha:6379/0"
        ports:
        - containerPort: 5000